crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from sales import views
from sales import crm_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login.as_view(),name='login'),
    url(r'^logout/', views.logout,name='logout'),
    url(r'^home/', views.homeVie,name='home'),
    url(r'^register/', views.register.as_view(), name='register'),
    url(r'^crm/', include(crm_urls)),
]

sales/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.core.validators import RegexValidator
from django.utils.safestring import mark_safe

# 课程表
course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),
                  ('Go', 'Golang高级开发'),
                  )

# 班级类型
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    )

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant')
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers',blank=True, null=True,  )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",blank=True, null=True,)
    class Meta:
        verbose_name = '客户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}-{}'.format(self.qq, self.name)
    # 自定义类的方法
    def show_class_list(self):
        return '|'.join([str(i) for i in self.class_list.all()])

    # 展示状态
    def show_status(self):
        _status_color = {
            'signed': 'blue',
            'unregistered': 'red',
            'studying': 'orange',
            'paid_in_full': 'green',
        }
        return mark_safe('<span style="background-color: {};color: white">{}</span>'.format(
            _status_color[self.status],
            self.get_status_display()
        ))
class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)
    class Meta:
        verbose_name = '校区'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
        verbose_name = '已报班级'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}-{}({})'.format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师")

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """
    学习记录
    """

sales/forms.py
from django import forms
from sales.models import UserProfile, Customer, ConsultRecord, Enrollment, ClassList
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

# ModelForm
class BootstrapBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 给实例对象的每一个字段添加class
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control form-group input-material'})

# ModeForm
class RegForm(BootstrapBaseForm):
    # 重写字段
    # name = forms.CharField(
    #     max_length=16,
    #     min_length=3,
    # )
    # password = forms.CharField(
    #     widget=forms.widgets.PasswordInput(),
    #     max_length=24,
    #     min_length=6,
    # )
    # 自定义字段
    re_password = forms.CharField(
        widget=forms.widgets.PasswordInput(
                attrs={
                    'placeholder': '确认密码',
                }),
        max_length=24,
        min_length=6,
        error_messages= {
                           "required": "密码不能为空",
                           "invalid": "格式错误",
                           "min_length": "密码最小为6位",
                           "max_length": "密码最长为24位",
                       },
    )

    # 类的配置
    class Meta:
        model = UserProfile  # 绑定 orm mode类
        # 展示要显示的字段
        fields = ['name', 'email', 'password', 're_password', 'mobile']
        # exclude = []  # 吧不需要展示的字段排除
        # 错误提示
        error_messages = {
            'name': {
                "required": "用户名不能为空",
                "invalid": "格式错误",
                "min_length": "用户名最小为3位",
                "max_length": "用户名最长为16位",
            },
            'mobile': {
                "required": "手机号不能为空",
                "invalid": "请输入正确手机号",
                "min_length": "请输入正确手机号",
                "max_length": "请输入正确手机号",
            },
            'password': {
                "required": "密码不能为空",
                "invalid": "格式错误",
                "min_length": "密码最小为6位",
                "max_length": "密码最长为24位",
            },

            'email': {
                "required": "邮箱不能为空",
                "invalid": "请输入正确邮箱地址",
                "min_length": "请输入正确邮箱地址",
                "max_length": "请输入正确邮箱地址",
            },
        }

        # labels 标签
        labels = {

        }

        # 插件
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={
                    'placeholder': '用户名',
                }),

            'email': forms.widgets.EmailInput(
                attrs={
                    'placeholder': '邮  箱',
                }
            ),
            'mobile': forms.widgets.TextInput(
                attrs={
                    'placeholder': '手机号',
                }
            ),
            'password': forms.widgets.PasswordInput(
                attrs={
                    'placeholder': '密  码',
                }
            ),

        }

    # # 初始化
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     for field in self.fields.values():
    #         field.widget.attrs.update({'class': 'form-group input-material'})



    # 检查邮箱是否被注册
    def clean_email(self):
        email_value = self.cleaned_data.get('email')
        is_exist = UserProfile.objects.filter(email=email_value)
        if is_exist:
            raise ValidationError('邮箱已被注册')
        else:
            return email_value
    # 检查手机号是否被注册
    def clean_mobile(self):
        mobile_value = self.cleaned_data.get('mobile')
        is_exist = UserProfile.objects.filter(mobile=mobile_value)
        if is_exist:
            raise ValidationError('手机号已被注册')
        else:
            return mobile_value

    # 检查两次密码输入是否一致
    def clean(self):
        pwd_value = self.cleaned_data.get('password')
        re_pwd_value = self.cleaned_data.get('re_password')
        if pwd_value == re_pwd_value:
            return self.cleaned_data
        else:
            self.add_error('re_password', '两次密码不一致')
            raise ValidationError('两次密码不一致')

# 编辑 FoRM
class CustomerForm(BootstrapBaseForm):
    # def __init__(self,*args,**kwargs):
    #     super(CustomerForm,self).__init__(*args,**kwargs)
    #     for field in self.fields.values():
    #         field.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'course': forms.widgets.SelectMultiple,
            'birthday': forms.widgets.DateInput(attrs={'type': 'date'}),
        }

# 沟通记录的form
class ConsultRecordForm(BootstrapBaseForm):
    class Meta:
        model = ConsultRecord
        exclude = ['delete_status', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 把customer字段的choice设置成我的客户
        print(self.instance, id(self.instance))
        print('&' * 120)
        # 方法1：修改字段的chocies选项
        # self.fields['customer'].choices = Customer.objects.filter(consultant=self.instance.consultant).values_list('id','name')
        # 方法2：将form表的字段直接修改字段
        self.fields['customer'] = forms.models.ModelChoiceField(queryset=Customer.objects.filter(consultant=self.instance.consultant))
        self.fields['customer'].widget.attrs.update({'class': 'form-control'})
        # 修改跟进人只能是自己
        self.fields['consultant'].choices = [(self.instance.consultant.id, self.instance.consultant.name), ]


# 报名表
class EnrollmentForm(BootstrapBaseForm):

    class Meta:
        model = Enrollment
        exclude = ['contract_approved', 'delete_status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 限制添加报名表的时候只能选自己私户
        # print(self.instance)
        self.fields['customer'].choices = [(self.instance.customer.id, self.instance.customer.name)]



# 班级表
class ClassListForm(BootstrapBaseForm):

    class Meta:
        model = ClassList
        fields = '__all__'

sales/templates/add_customer.html
{% extends 'base.html' %}

{% block page-main %}
    <div>
        <h2 class="text-center">录入客户信息</h2>
        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if  field.errors.0 %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

sales/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>客户展示页面</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
    {% block page-css %}

    {% endblock %}
</head>

<body>

{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'customer_list' %}">客户列表</a></li>
                <li><a href="{% url 'my_customer' %}#">我的客户</a></li>
                <li><a href="{% url 'consult_record' 0 %}">跟进记录</a></li>
                <li><a href="{% url 'enrollment_list' 0 %}">查看报名表</a></li>
{#                <li><a href="{% url 'class_list' %}">班级列表</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block page-main %}

            {% endblock %}
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.js' %}"></script>
{% block page-js %}

{% endblock %}
</body>
</html>

sales/templates/consult_record.html
{% extends 'base.html' %}

{% block page-main %}
    <div>
        <h2 class="text-center">{% if edit_id %}编辑沟通记录{% else %}添加沟通记录{% endif %}</h2>
        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if  field.errors.0 %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

sales/templates/consult_record_list.html
{% extends 'base.html' %}

{% block page-main %}
    <h2 class="sub-header">沟通记录</h2>
    <div class="col-md-12">
        <a href="{% url 'add_record' %}" class="btn btn-success btn-sm">添加</a>
        <div class="col-md-4 pull-right">
            <form action="" method="get" enctype="application/x-www-form-urlencoded">
                <div class="input-group">
                    <input type="text" name="query" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="submit">搜呀</button>
      </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="col-md-3" style="margin: 5px 0">
            <div class="input-group">
                <select class="form-control" name="action">
                    <option value="">---------</option>
                    <option value="to_public">变为公户</option>
                    <option value="to_private">变为私户</option>
                    <option value="delete">删除</option>
                </select>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th style="width: 20px">选择</th>
                        <th style="width: 20px">#</th>
                        <th style="width: 80px">客户qq</th>
                        <th style="width: 80px">客户姓名</th>
                        <th style="width: 80px">跟进内容</th>
                        <th style="width: 60px">跟进状态</th>
                        <th style="width: 80px">跟进人</th>
                        <th style="width: 90px">跟进日期</th>
                        <th style="width: 20px!important;">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for record in consult_record %}
                        <tr>
                            <td><input type="checkbox" name="cid" value="{{ record.id }}"></td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ record.customer.qq }}</td>
                            <td>{{ record.customer.name }}</td>
                            <td>{{ record.note }}</td>
                            <td>{{ record.get_status_display }}</td>
                            <td>{{ record.consultant.name }}</td>
                            <td>{{ record.date }}</td>
                            <td><a href="{% url 'edit_record' record.id %}"><i class="fa fa-edit"
                                                                                   aria-hidden="true"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div>
                    {{ page_html|safe }}
                </div>
            </div>
        </div>

    </form>
{% endblock %}

sales/templates/customer_list.html
{% extends 'base.html' %}
{% block page-main %}
<h2 class="sub-header">客户列表</h2>
{#    添加用户按钮 #}
<div>
{#    <a href="{% url 'add_customer' %}" class="btn btn-success btn-sm">添加</a>#}
<a href="{% url 'add_customer' %}?next={{ request.get_full_path }}" class="btn btn-success btn-sm">添加</a>
    <div class="col-md-4 pull-right">
        <form action="" method="get" enctype="application/x-www-form-urlencoded">
            <div class="input-group">
                <input type="text" name="query" class="form-control" placeholder="模糊搜索 ...">
                <span class="input-group-btn">
        <button class="btn btn-default" type="submit">搜索</button>
      </span>
            </div><!-- /input-group -->
        </form>
    </div>
</div>
    <form action="" method="post">
    {% csrf_token %}
    <div class="col-md-3" style="margin: 5px 0">
        <div class="input-group">
            <select class="form-control" name="action">
                <option value="">---------</option>
                <option value="to_public">变为公户</option>
                <option value="to_private">变为私户</option>
                <option value="delete">删除</option>
            </select>
            <div class="input-group-btn">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </div>
    </div>
    <div class="col-md-12">
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th style="width: 20px">操作</th>
            <th style="width: 20px">#</th>
            <th style="width: 80px">QQ</th>
            <th style="width: 80px">QQ昵称</th>
            <th style="width: 60px">姓名</th>
            <th style="width: 80px">电话</th>
            <th style="width: 90px">客户来源</th>
            <th style="width: 120px">咨询课程</th>
            <th style="width: 60px">招生老师</th>
            <th style="width: 60px">班级类型</th>
            <th style="width: 60px">状态</th>
            <th style="width: 100px">咨询日期</th>
            <th style="width: 120px!important;">已报班级</th>
            <th style="width: 120px!important;">沟通记录</th>
            <th style="width: 120px!important;">报名</th>
            <th style="width: 20px!important;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for customer in customer_list %}
        <tr>
            <td><input type="checkbox" name="cid" value="{{ customer.id }}"></td>
            <td>{{ forloop.counter }}</td>
            <td>{{ customer.qq }}</td>
            <td>{{ customer.qq_name }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.phone|default:'暂无' }}</td>
            <td>{{ customer.get_source_display }}</td>
            <td>{{ customer.course }}</td>
            <td>{{ customer.consultant|default:'暂无' }}</td>
            <td>{{ customer.get_class_type_display }}</td>
            <td>{{ customer.show_status|default:'暂无'}}</td>
            <td>{{ customer.date|date:'Y-m-d' }}</td>
            <td>{{ customer.show_class_list|default:'暂无' }}</td>
            <td><a href="{% url 'consult_record' cid=customer.id %}">查看</a></td>
            <td>
                <a href="{% url 'add_enrollment' customer.id %}">添加</a> |
                <a href="{% url 'enrollment_list' customer.id %}">查看</a>
            </td>

            <td><a href="{% url 'edit_customer' customer.id %}?{{ next_url }}"><i class="fa fa-edit"
                                                                           aria-hidden="true"></i></a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>
        {{ page_html|safe }}
    </div>
</div></div>
        </form>

{% endblock %}

sales/templates/enrollment.html
{% extends 'base.html' %}

{% block page-main %}
    <div>
        <h2 class="text-center">{% if edit_id %}编辑报名表{% else %}添加报名表{% endif %}</h2>
        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if  field.errors.0 %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block page-js %}
    {% load static %}
    <script src="{% static 'jquery.js' %}"></script>
    <script>
    $(document).ready(function () {
        $('#id_school').on('change', function () {
            var sId = $(this).val();
            // 获取到选中的校区id
            // 发AJAX到后端取出当前校区下面所有的课程
            $.ajax({
                url: '/crm/ajax_class/',
                type: 'get',
                data: {'sid': sId},
                success: function (res) {
                    console.log(res);
                    var $classSelect = $('#id_enrolment_class');
                    $classSelect.text('');
                    $classSelect.append('<option value="">-------</option>');
                    $.each(res.data, function (k, v) {
                        console.log(k, v);
                        var opEle = document.createElement('option');
                        $(opEle).text(v.name).attr('value', v.id);
                        $classSelect.append(opEle);
                    })
                }
            })
        })
    })
    </script>
{% endblock %}

sales/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>home</h1>

<a href="/logout/">注销</a>
</body>
</html>